Repository epinio/epinio-end-to-end-tests, pull requests merged in 2022-02, with the labels that each got.

#66 Add scenario 2 to CI (s3/ext_reg)
  .github/workflows/master_ui_workflow.yml
  .github/workflows/scenario_2_cypress_firefox.yml
Labels: QA

#67 Add user option for firefox browser
  .github/workflows/master_ui_workflow.yml
  .github/workflows/scenario_2_cypress_firefox.yml
Labels: QA

#74 Don't log sensitive informations like credentials
  cypress/support/epinio.ts
  cypress/support/functions.ts
  cypress/support/index.ts
Labels: QA

#83 Use k3s v1.21 + permissions fixes
  .github/workflows/master_ui_workflow.yml
  Makefile
Labels: QA

#84 Add some fixes
  .github/workflows/master_ui_workflow.yml
  Makefile
  cypress/support/functions.ts
Labels: QA

#86 A `if always` was missing for the cleaning step
  .github/workflows/master_ui_workflow.yml
Labels: bug, QA

#87 fix: Rename the tests badges
  .github/workflows/scenario_1_cypress_chrome.yml
  .github/workflows/scenario_2_cypress_firefox.yml
  README.md
Labels: QA

#89 fix: show only the scheduled actions in badges link
  README.md
Labels: QA

#90 Test service unbinding
  cypress/support/functions.ts
  cypress/support/index.ts
  cypress/support/tests.ts
Labels: enhancement

#96 Small fixes in Rancher installation
  scripts/install_rancher.sh
Labels: QA
