Repository epinio/epinio-end-to-end-tests, pull requests merged in 2023-03, with the labels that each got.

#300 Cypress/299 automate dashboard page
  cypress/e2e/unit_tests/menu.spec.ts
  cypress/support/e2e.ts
  cypress/support/functions.ts
  cypress/support/tests.ts
Labels: area/qa

#303 Add ghcr.io secrets for pulling images
  .github/workflows/master_rancher_ui_experimental_workflow.yml
  .github/workflows/master_rancher_ui_workflow.yml
  .github/workflows/master_std_ui.yml
  .github/workflows/master_std_ui_experimental.yml
  scripts/create_docker_secret.sh
Labels: kind/enhancement, area/qa

#304 Fix secret references
  .github/workflows/master_rancher_ui_experimental_workflow.yml
  .github/workflows/master_rancher_ui_workflow.yml
  .github/workflows/scenario_1_chrome_rancher_ui.yml
  .github/workflows/scenario_2_firefox_rancher_ui.yml
Labels: kind/bug, area/qa

#306 Cypress Adding s3gw test in Rancher.
  cypress/e2e/unit_tests/installation.spec.ts
  cypress/support/e2e.ts
  cypress/support/functions.ts
Labels: area/qa
